### ISSUE TITLE
How to fix problem about date time?

### ISSUE THREAD

**Issue by lkittyzaa** [ashishd751/react-excel-renderer#1]
I insert excel  file but date on excel such as 14/03/2019  not show .
It show 42917.  if I want to get value date.
How to solve this problem ?

**Comment by ashishd751** [comment]
Irrespective of whether the content is plain text or date or anything else for that matter, it must be displayed exactly as it is.

Are you sure it's displaying the value 42917 for all date type cells ?

Could you also please provide a screenshot of this value against the original excel ? 

P.S - Is the date value obtained from any excel formula in the sheet ?

**Comment by lkittyzaa** [comment]
[S1-A.xlsx](https://github.com/ashishd751/react-excel-renderer/files/2964751/S1-A.xlsx)

This is my file excel. I uploaded already. Date is in column A2 (Date)  such as 1/9/2017.

and when I test by import this excel in https://ashishd751.github.io/excel-renderer-demo/.
the result show like this picture.
![image](https://user-images.githubusercontent.com/42953134/54332120-5b526d00-464f-11e9-98b2-fd25130307df.png) 
At  column A2 show 42979. Could you  advise me about this.  Thank you.

**Comment by ffesteban** [comment]
I have the same problem, the content extracted from the Excel file is not displaying the same text, it looks like on some dates the value is parsed like a number so it misses the date format.

**Comment by prateekroopra** [comment]
Any updates on this?

**Comment by IncWolf** [comment]
That issue is linked with sheetjs and is explained here: https://github.com/SheetJS/sheetjs/issues/721#issuecomment-313732443

We need to set cellDates to true to show sheetjs that we need to get XLS date numeric codes as date objects

**Comment by prasid444** [comment]
Any updates yet?

**Comment by eugene2candy** [comment]
@lkittyzaa @prasid444 @prateekroopra @ffesteban 
Hello guys, I faced the same issue. But I found a solution to convert the number to date. 
Actually it's a DATAVALUE in excel, so you can convert it like below: 

> export const getJsDateFromExcel = excelDate => {
>     return new Date((excelDate - (25567 + 1)) * 86400 * 1000);
> };

**Comment by HusamGI** [comment]
Hello, if any one is facing this issue here's the solution that worked for me:
[https://stackoverflow.com/a/68114202/2078322](https://stackoverflow.com/a/68114202/2078322)
Thanks to [ahsan mukhtar](https://stackoverflow.com/users/12636204/ahsan-mukhtar)
