### ISSUE TITLE
Error to install and run

### ISSUE THREAD

**Issue by DianneGdLk** [ashishd751/react-excel-renderer#2]
Try to run the example but -
Could not find a declaration file for module 'react-excel-renderer'. 'c:/Users/nb50502/Source/GulfCoastQualityControl/FrontEnd/node_modules/react-excel-renderer/build/index.js' implicitly has an 'any' type.
  Try `npm install @types/react-excel-renderer` if it exists or add a new declaration (.d.ts) file containing `declare module 'react-excel-renderer';`

**Comment by lkittyzaa** [comment]
When install I used :   "  npm install react-excel-renderer --save "  
And Declaration I used : " import {OutTable, ExcelRenderer} from 'react-excel-renderer'; "
the result : It's work. This library  is suitable for ReactJs.

**Comment by ashishd751** [comment]
Please note that, as the name suggests, this library was built for and works only with React JS.

**Comment by DianneGdLk** [comment]
Did the same. But not working
