### ISSUE TITLE
Infinite loop when xlsx file has 2 lines with 1 empty value

### ISSUE THREAD

**Issue by francoisruty** [ashishd751/react-excel-renderer#6]
Hello, first of thanks for your lib, it's awesome.
I've installed the npm package version  1.1.0.

I've been able to visualize excel files in my simple app so it's great.

However, I have one particular xlsx file that, when uploaded, crashes the browser tab in which the web app is running. I've checked, it's the ExcelRenderer that is stuck in an infinite loop, and it's before the callback so not in my code.
This excel file has bogus data, has only 2 lines, and the particularity is that it has one missing value on the second line.
I don't know why this exact configuration triggers the crash, but here is the excel file:

[pg_model_err.xlsx](https://github.com/ashishd751/react-excel-renderer/files/4010264/pg_model_err.xlsx)

**Comment by francoisruty** [comment]
I just noticed that the empty value is irrelevant, I also have the problem with any xlsx file with 2 full lines. I don't know what conditions trigger this bug, except that the file I uploaded does.
I'm interested in your opinion!

**Comment by ashishd751** [comment]
Hey,

Thank you for informing me about the bug.

I'll try to replicate it, and let you know.
In the meantime, if you're in a hurry, feel free to fork and inspect it
yourselves.

Have a great day and a happy new year. Cheers.


Regards,
*Ashish Deshpande*

**Comment by francoisruty** [comment]
I'm working on a prototype so no hurry on my side, if it's validated to go to production (should be decided in 1 month) I'll need to fix it indeed if you hadn't had time on your side yet
thanks and happy new year!

**Comment by francoisruty** [comment]
Side note: the infinite loop seems to come from the fact that the lib just reads all empty lines at the bottom of the xlsx file. So the lib actually works, you end up with the results, but the callback sends you like 2M rows and this is what crashes the browser

**Comment by mgu-shs** [comment]
Was this ever fixed (if it need a fix)? 

I'm trying to load a file with a few rows of data, but the callback gives me 200k rows with nothing, taking a long time to process the file instead of just returning the first N rows with data
